#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MOBILE_NOITE.Resource", IsApplication=true)]

namespace MOBILE_NOITE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baseline_android_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int baseline_event_seat_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int baseline_face_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ios = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PROJETO = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int XAMARIN = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int AtividadeAlertDialog = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int AtividadeRadioButonImageView = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int AutoComplet = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int AutoComplete = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int IOS = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int ViewAutoCompletTextView = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int ViewImageView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int ViewRadioButton = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int WidgetAula01 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int WiewAlertDialog = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int android = 2131034115;
			
			// aapt resource value: 0x7f050018
			public const int bt = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int btAlert = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int btAlertOkNo = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int btPer = 2131034117;
			
			// aapt resource value: 0x7f05001c
			public const int btToast = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int campoNome = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int img01 = 2131034112;
			
			// aapt resource value: 0x7f050011
			public const int imgAndr = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int imgIos = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int imgv = 2131034128;
			
			// aapt resource value: 0x7f050019
			public const int mostra = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int mostraPer = 2131034118;
			
			// aapt resource value: 0x7f050014
			public const int rd01 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int rd02 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int rd03 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int rd04 = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int xamarin = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int xamrin = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ATIVIDADE2_RADIOBUTTON_IMAGEVIEW = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Atividade_AlertDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AULAS = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewAutoCompletTextView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewImageView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ViewRadioButton = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WidgetAula01 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int WiewAlertDialog = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int bt_ViewAutoCompletTextView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int bt_ViewImageView = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int bt_ViewRadioButton = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int bt_WidgetAula01 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int bt_WiewAlertDialog = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int bt_atividade01 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int bt_atividade02 = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int bt_complet = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int estado = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
